"""Creating client table

Revision ID: 02d9125c693f
Revises: 
Create Date: 2025-03-02 12:19:11.362241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02d9125c693f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('client_id', sa.String(length=16), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('device_type', sa.Enum('edge', 'cloud', 'local'), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive'), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('api_key_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('client_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client')
    # ### end Alembic commands ###
