"""Creating table for client updates

Revision ID: cd235eff8155
Revises: 02d9125c693f
Create Date: 2025-03-06 17:43:59.193889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd235eff8155'
down_revision = '02d9125c693f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('update',
    sa.Column('update_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.String(length=16), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('type', sa.Enum('train', 'load', 'update'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'completed'), nullable=False),
    sa.Column('updated_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.client_id'], ),
    sa.PrimaryKeyConstraint('update_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('update')
    # ### end Alembic commands ###
